[package]
name = "eth_driver"
version = "0.1.0"
edition = "2021"

[dependencies]
smos-runtime = { path = "../smos-runtime" }
smos-cspace = { path = "../smos-cspace" }
smos-common = { path = "../smos-common"}