[v1]
"sel4-kernel-loader 0.1.0 (git+https://github.com/seL4/rust-sel4#b212a56b621c1c7a9d9c54e48f6ebeab34cd37c5)" = ["sel4-kernel-loader"]
"sel4-kernel-loader-add-payload 0.1.0 (git+https://github.com/seL4/rust-sel4#b212a56b621c1c7a9d9c54e48f6ebeab34cd37c5)" = ["sel4-kernel-loader-add-payload"]
