#
# Copyright 2023, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

[workspace]

resolver = "2"

members = [
    "crates/root_server", "crates/smos-runtime", "crates/smos-server",
    "crates/test_app"
]
