#!/bin/bash

meson compile -C build || exit 1

qemu-system-aarch64 \
	-machine virt,virtualization=on \
	-cpu cortex-a57 -m size=2G \
	-serial mon:stdio \
	-global virtio-mmio.force-legacy=false \
	-device virtio-net-device,netdev=netdev0 \
	-netdev user,id=netdev0,hostfwd=tcp::1236-:1236,hostfwd=udp::1235-:1235 \
	-device virtio-serial-device -chardev pty,id=virtcon -device virtconsole,chardev=virtcon \
	-nographic \
	-kernel build/image.elf
