// @alwin: This file should probably be autogenerated

#[repr(usize)]
pub enum WindowCreateArgs {
    BaseVaddr = 0,
    Size = 1,
    ReturnCap = 2,
}

#[repr(usize)]
pub enum WindowDestroyArgs {
    Handle = 0,
}

#[repr(usize)]
pub enum ConnectionDestroyArgs {
    Handle = 0,
}

#[repr(usize)]
pub enum ObjCreateArgs {
    HasName = 0,
    Size,
    Rights,
    Attributes,
    ReturnCap,
    Length,
}

#[repr(usize)]
pub enum ViewArgs {
    Window = 0,
    Object,
    WinOffset,
    ObjOffset,
    Size,
    Rights,
    Length,
}
