// @alwin: This file should probably be autogenerated

#[repr(usize)]
pub enum WindowCreateArgs {
	Base_Vaddr = 0,
	Size = 1,
	ReturnCap = 2
}

#[repr(usize)]
pub enum WindowDestroyArgs {
	Handle = 0
}

#[repr(usize)]
pub enum ConnectionDestroyArgs {
	Handle = 0
}

#[repr(usize)]
pub enum ObjCreateArgs {
	HasName = 0,
	Size = 1,
	Rights = 2,
	ReturnCap = 3,
}

pub enum ViewArgs {
	Window = 0,
	Object = 1,
	WinOffset = 2,
	ObjOffset = 3,
	Size = 4,
	Rights = 5,
}