name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  style:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Check style
      run: cargo fmt --all -- --check
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: ./loader.sh
    - name: Initialize submodules
      run: |
        git submodule init
        git submodule update --recursive
    - name: Build project
      run: |
        meson setup --cross-file meson-toolchain.txt build
        meson compile -C build
